name: Monitor Application Health

on:
  schedule:
    # Проверяем каждые 30 минут
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub Pages
        id: gh-pages
        run: |
          URL="https://sarkisisraelyan.github.io/CalmBrew-"
          if curl -f -s "$URL" > /dev/null; then
            echo "status=online" >> $GITHUB_OUTPUT
            echo "✅ GitHub Pages работает: $URL"
          else
            echo "status=offline" >> $GITHUB_OUTPUT
            echo "❌ GitHub Pages недоступен: $URL"
          fi
      
      - name: Check response time
        if: steps.gh-pages.outputs.status == 'online'
        run: |
          URL="https://sarkisisraelyan.github.io/CalmBrew-"
          RESPONSE_TIME=$(curl -w "%{time_total}" -s -o /dev/null "$URL")
          echo "⏱️ Время ответа: ${RESPONSE_TIME}s"
          
          # Проверяем критическое время ответа
          if (( $(echo "$RESPONSE_TIME > 5" | bc -l) )); then
            echo "⚠️ Медленный ответ: ${RESPONSE_TIME}s"
            exit 1
          fi
      
      - name: Check bot status
        run: |
          BOT_USERNAME="CalmBrew_Bot"
          BOT_URL="https://t.me/$BOT_USERNAME"
          echo "🤖 Проверяем бота: $BOT_URL"
          echo "ℹ️ Статус бота можно проверить вручную"
      
      - name: Generate report
        run: |
          echo "## 📊 Отчет о состоянии приложения" >> report.md
          echo "" >> report.md
          echo "**Время проверки:** $(date)" >> report.md
          echo "**GitHub Pages:** ${{ steps.gh-pages.outputs.status }}" >> report.md
          echo "**Статус:** ${{ job.status }}" >> report.md
          echo "" >> report.md
          echo "### 🔗 Ссылки:" >> report.md
          echo "- 🌐 Сайт: https://sarkisisraelyan.github.io/CalmBrew-" >> report.md
          echo "- 🤖 Бот: https://t.me/CalmBrew_Bot" >> report.md
          echo "- 📁 Репозиторий: https://github.com/Sarkisyan444/CalmBrew-" >> report.md
      
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: health-report
          path: report.md

  notify:
    runs-on: ubuntu-latest
    needs: health-check
    if: always()
    steps:
      - name: Download report
        uses: actions/download-artifact@v3
        with:
          name: health-report
      
      - name: Show status
        run: |
          if [ -f report.md ]; then
            echo "📋 Отчет о состоянии:"
            cat report.md
          fi
          
          if [ "${{ needs.health-check.result }}" == "success" ]; then
            echo "✅ Все проверки прошли успешно!"
          else
            echo "⚠️ Обнаружены проблемы!"
          fi
